# Generated by Django 3.2.6 on 2021-08-30 23:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('score', models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('known', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('x1', models.FloatField(blank=True, default=None, null=True)),
                ('x2', models.FloatField(blank=True, default=None, null=True)),
                ('y1', models.FloatField(blank=True, default=None, null=True)),
                ('y2', models.FloatField(blank=True, default=None, null=True)),
                ('calculated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Consensus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('score', models.FloatField(blank=True, default=None, null=True)),
                ('x1_lower', models.FloatField(blank=True, default=None, null=True)),
                ('x1_upper', models.FloatField(blank=True, default=None, null=True)),
                ('x2_lower', models.FloatField(blank=True, default=None, null=True)),
                ('x2_upper', models.FloatField(blank=True, default=None, null=True)),
                ('y1_lower', models.FloatField(blank=True, default=None, null=True)),
                ('y1_upper', models.FloatField(blank=True, default=None, null=True)),
                ('y2_lower', models.FloatField(blank=True, default=None, null=True)),
                ('y2_upper', models.FloatField(blank=True, default=None, null=True)),
                ('annotation_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('spam_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('annotators', models.ManyToManyField(to='label_api.Annotator')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='label_api.image')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('x1', models.FloatField(default=0)),
                ('x2', models.FloatField(default=0)),
                ('y1', models.FloatField(default=0)),
                ('y2', models.FloatField(default=0)),
                ('x1_out', models.BooleanField(default=False)),
                ('x2_out', models.BooleanField(default=False)),
                ('y1_out', models.BooleanField(default=False)),
                ('y2_out', models.BooleanField(default=False)),
                ('spam', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('point', models.FloatField(blank=True, default=None, null=True)),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='label_api.annotator')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='label_api.image')),
            ],
        ),
    ]
